// web-vue/pages/downloads.vue
<template>
  <v-container>
    <download-card v-for="item in items" :id="item.id" :key="item.id" />
  </v-container>
</template>

<script>
import DownloadCard from '../components/DownloadCard.vue'

export default {
  components: {
    DownloadCard,
  },
  data() {
    return {
      items: [],
    }
  },
  head() {
    return {
      title: 'Waik | Letoltések',
      meta: [
        {
          name: 'og:title',
          content: 'Waik | Letoltések',
        },
        {
          name: 'og:description',
          content:
            'Itt találhatod meg a waik csapattal kapcsolatos letoltheto dolgokat',
        },
        {
          name: 'og:image',
          content:
            'https://firebasestorage.googleapis.com/v0/b/zal1000.net/o/waik%2Fpublic%2Fwaik_cup.jpg?alt=media&token=5c3a6c28-644a-492a-ba4d-74d9e52470e2',
        },
      ],
    }
  },
  async created() {
    const db = this.$fire.firestore
    const query = db
      .collection('waik/website/downloads')
      .where('visible', '==', true)
      .orderBy('timestamp')
    const queryres = await query.get()
    let a = []
    a = queryres.docs
    this.items = a.reverse()
  },
}
</script>

<style
DownloadCard>
</style>

// web-old/src/app/downloads/downloads.component.ts
import { Component, OnInit } from '@angular/core';
import { MessagesService } from '../services/messages.service';
import { Meta, Title } from '@angular/platform-browser';

import { collection, getDocs, getFirestore, orderBy, query, where } from 'firebase/firestore';

@Component({
  selector: 'app-downloads',
  templateUrl: './downloads.component.html',
  styleUrls: ['./downloads.component.scss'],
})
export class DownloadsComponent implements OnInit {
  colldata: Docdata[] = [];

  isFromPhone: boolean = false;

  db = getFirestore();

  constructor(
    private htmltitle: Title,
    private msg: MessagesService,
    private meta: Meta,
  ) {}

  ngOnInit(): void {
    this.isFromPhone = this.detectMob();
    //const coll = this.db.collection('waik').doc('website').collection('downloads', (ref) => ref.orderBy('timestamp'));
    this.htmltitle.setTitle('Waik | Letöltések');
    this.meta.addTag({ property: 'og:title', content: 'Waik | Letöltések' });
    this.meta.addTag({
      property: 'og:image',
      content:
        'https://firebasestorage.googleapis.com/v0/b/zal1000.net/o/waik%2Fpublic%2Fwaik_cup.jpg?alt=media&token=5c3a6c28-644a-492a-ba4d-74d9e52470e2',
    });
    this.meta.addTag({
      property: 'og:description',
      content: 'Itt találhatóak a letölthető dolgok a waik csapattal kapcsolatban',
    });
    this.meta.addTag({ property: 'twitter:site', content: 'https://waik.hu/' });
    this.meta.addTag({
      property: 'twitter:creator',
      content: '@zal1000original',
    });
    this.meta.addTag({ property: 'twitter:image:alt', content: 'Waik' });
    this.meta.addTag({ property: 'fb:app_id', content: '581458672492860' });
    this.meta.addTag({ property: 'og:url', content: 'https://waik.hu/' });
    const q = query(collection(this.db, 'waik/website/downloads'), where('visible', '==', true), orderBy('timestamp'));
    
    getDocs(q).then(coll => {
      for (const doc of coll.docs) {
        const docdata: any = doc.data();
        this.colldata.push(docdata);
      }

      this.colldata.reverse();
    }).catch(e => {
      this.msg.error(e.message)
    });
  }

  detectMob() {
    const toMatch = [
        /Android/i,
        /webOS/i,
        /iPhone/i,
        /iPad/i,
        /iPod/i,
        /BlackBerry/i,
        /Windows Phone/i
    ];

    return toMatch.some((toMatchItem) => {
        return navigator.userAgent.match(toMatchItem);
    });
  }
}

interface Docdata {
  desc: string | null;
  downloadgs: string | null;
  downloadurl: string | null;
  githuburl: string | null;
  imageurl: string | null;
  name: string;
  shareid: string | null;
  author: string | undefined;
}

<mat-progress-bar *ngIf="colldata.length === 0" mode="indeterminate"></mat-progress-bar>
<div *ngIf="!isFromPhone">
  <div fxLayout="row wrap" class="div" *ngIf="colldata.length != 0">
    <div fxLayout="row wrap" fxLayoutGap="16px" style="margin: 16px;" *ngFor="let doc of colldata">
      <app-card
        [title]="doc.name"
        [dlurl]="doc.downloadurl"
        [gsurl]="doc.downloadgs"
        [image]="doc.imageurl"
        [github]="doc.githuburl"
        [desc]="doc.desc"
        [shareid]="doc.shareid"
        [author]="doc.author"
      ></app-card>
    </div>
  </div>
</div>

<div *ngIf="isFromPhone">
  <div fxLayout="row wrap" style="margin: 2.5vw;" *ngIf="colldata.length != 0">
    <div fxLayout="row wrap" fxLayoutGap="16px" style="margin-bottom: 10px;" *ngFor="let doc of colldata">
      <app-card
        [title]="doc.name"
        [dlurl]="doc.downloadurl"
        [gsurl]="doc.downloadgs"
        [image]="doc.imageurl"
        [github]="doc.githuburl"
        [desc]="doc.desc"
        [shareid]="doc.shareid"
        [author]="doc.author"
      ></app-card>
    </div>
  </div>
</div>

<!--
<div>
  <div class="center">
    <mat-spinner></mat-spinner>
  </div>
</div>
-->


<app-footer *ngIf="!isFromPhone" [extraIds]="[{ 'id': '406516981110407168', role:'idea', name: null, avatarurl: null }]"></app-footer>
