// web/src/app/profiles/norticus/norticus.component.ts
import { Component, OnInit } from '@angular/core';
import { doc, getDoc, getFirestore } from 'firebase/firestore';

@Component({
  selector: 'app-norticus',
  templateUrl: './norticus.component.html',
  styleUrls: ['./norticus.component.scss']
})
export class NorticusComponent implements OnInit {
  db = getFirestore();
  pp: string = "https://cdn.discordapp.com/avatars/118466559738904576/6b4610199259efab8493cafb3e049938.webp";
  name: string = "Norticus36#7832";
  
  desc: string  = `Sziasztok! Norticus (Todi) vagyok, főként számítógépes játékokkal és
  az informatikával foglalkozom. Néha talán túlságosan is versengő
  vagyok a mentális jólétemnek. Ha játékokról vagy animékről van szó,
  szívesen elbeszélgetek róluk. Jelenleg informatikushallgató vagyok, de
  igyekszem időt szánni magamra és a streamelésre is. A waik csapat
  egyik alapító tagja vagyok (fun fact, az eredeti waik figurához
  egyedül én nem rajzoltam hozzá, mire odaértem már véglegesítve lett),
  a szervereket amin a csapat játszik legtöbbször én hosztolom.
  Igyekszem élőben is közvetíteni a történéseket, ha új sorozat készül
  éppen, akkor én (és néha Isti) streameljük élőben, de szoktam egyedül
  is streamelni, akár angolul is.`
  constructor() { }

  ngOnInit(): void {

    const tdrRef = doc(this.db, 'dcusers/118466559738904576');

    getDoc(tdrRef).then(res => {
      this.pp = res.data()?.pp
    })
  }

}

<div fxLayout="row wrap" class="div">
  <div fxLayout="row wrap" fxLayoutGap="16px" style="margin: 16px">
    <mat-card class="card">
      <mat-card-header>
        <div mat-card-avatar class="example-header-image">
          <img height="45" class="rounded-circle" [src]="pp" />
        </div>
        <mat-card-title>Norticus</mat-card-title>
        <mat-card-subtitle>Bemutatkozás</mat-card-subtitle>
      </mat-card-header>
      <mat-card-content>
        <p class="text">
          {{ desc }}
          
        </p>
      </mat-card-content>
    </mat-card>
  </div>
</div>

<!--
    <iframe src="https://player.twitch.tv/?channel=norticus36&parent=www.example.com" frameborder="0" allowfullscreen="true" scrolling="no" height="378" width="620"></iframe>
  -->

// web/pages/profiles/norticus.vue

<template>
  <div>
    <social-bar user="norticus"></social-bar>
    <description-card style="margin-top: 30px;" :desc="desc" :imageurl="imageurl" :name="name"></description-card>
  </div>
</template>

<script>
import SocialBar from '../../components/SocialBar.vue'
import DescriptionCard from '../../components/DescriptionCard.vue'
export default {
  components: { SocialBar, DescriptionCard },
  data() {
    return {
      name: 'Norticus',
      imageurl:
        'https://cdn.discordapp.com/avatars/118466559738904576/6b4610199259efab8493cafb3e049938.webp',
      dctag: 'Norticus36#7832',
      color: '#278003',
      desc: 'Sziasztok! Norticus (Todi) vagyok, főként számítógépes játékokkal és az informatikával foglalkozom. Néha talán túlságosan is versengő vagyok a mentális jólétemnek. Ha játékokról vagy animékről van szó, szívesen elbeszélgetek róluk. Jelenleg informatikushallgató vagyok, de igyekszem időt szánni magamra és a streamelésre is. A waik csapat egyik alapító tagja vagyok (fun fact, az eredeti waik figurához egyedül én nem rajzoltam hozzá, mire odaértem már véglegesítve lett), a szervereket amin a csapat játszik legtöbbször én hosztolom. Igyekszem élőben is közvetíteni a történéseket, ha új sorozat készül éppen, akkor én (és néha Isti) streameljük élőben, de szoktam egyedül is streamelni, akár angolul is.',
      loading: false,
    }
  },
  head() {
    return {
      title: `Waik | ${this.name}`,
      meta: [
        {
          name: 'og:title',
          content: `Waik | ${this.name}`,
        },
        {
          name: 'description',
          content: this.desc,
        },
        {
          name: 'og:description',
          content: this.desc,
        },
        {
          name: 'og:image',
          content: this.imageurl,
        },
        {
          name: 'og:image:secure_ur',
          content: this.imageurl,
        },
        {
          name: 'og:image:alt',
          content: this.name,
        },
        {
          name: 'theme-color',
          content: this.color,
        },
      ],
    }
  },
}
</script>

<style>
</style>
